/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWhatsappRouteImport } from './routes/_app.whatsapp'
import { Route as AppTemplatesRouteImport } from './routes/_app.templates'
import { Route as AppSopRouteImport } from './routes/_app.sop'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppQuizRouteImport } from './routes/_app.quiz'
import { Route as AppProposalRouteImport } from './routes/_app.proposal'
import { Route as AppKontrakRouteImport } from './routes/_app.kontrak'
import { Route as AppFinancialRouteImport } from './routes/_app.financial'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBillingRouteImport } from './routes/_app.billing'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSopRoute = AppSopRouteImport.update({
  id: '/sop',
  path: '/sop',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizRoute = AppQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AppRoute,
} as any)
const AppProposalRoute = AppProposalRouteImport.update({
  id: '/proposal',
  path: '/proposal',
  getParentRoute: () => AppRoute,
} as any)
const AppKontrakRoute = AppKontrakRouteImport.update({
  id: '/kontrak',
  path: '/kontrak',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancialRoute = AppFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/financial': typeof AppFinancialRoute
  '/kontrak': typeof AppKontrakRoute
  '/proposal': typeof AppProposalRoute
  '/quiz': typeof AppQuizRoute
  '/settings': typeof AppSettingsRoute
  '/sop': typeof AppSopRoute
  '/templates': typeof AppTemplatesRoute
  '/whatsapp': typeof AppWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/financial': typeof AppFinancialRoute
  '/kontrak': typeof AppKontrakRoute
  '/proposal': typeof AppProposalRoute
  '/quiz': typeof AppQuizRoute
  '/settings': typeof AppSettingsRoute
  '/sop': typeof AppSopRoute
  '/templates': typeof AppTemplatesRoute
  '/whatsapp': typeof AppWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/financial': typeof AppFinancialRoute
  '/_app/kontrak': typeof AppKontrakRoute
  '/_app/proposal': typeof AppProposalRoute
  '/_app/quiz': typeof AppQuizRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sop': typeof AppSopRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/whatsapp': typeof AppWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/billing'
    | '/dashboard'
    | '/financial'
    | '/kontrak'
    | '/proposal'
    | '/quiz'
    | '/settings'
    | '/sop'
    | '/templates'
    | '/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/billing'
    | '/dashboard'
    | '/financial'
    | '/kontrak'
    | '/proposal'
    | '/quiz'
    | '/settings'
    | '/sop'
    | '/templates'
    | '/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/billing'
    | '/_app/dashboard'
    | '/_app/financial'
    | '/_app/kontrak'
    | '/_app/proposal'
    | '/_app/quiz'
    | '/_app/settings'
    | '/_app/sop'
    | '/_app/templates'
    | '/_app/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sop': {
      id: '/_app/sop'
      path: '/sop'
      fullPath: '/sop'
      preLoaderRoute: typeof AppSopRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quiz': {
      id: '/_app/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AppQuizRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/proposal': {
      id: '/_app/proposal'
      path: '/proposal'
      fullPath: '/proposal'
      preLoaderRoute: typeof AppProposalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kontrak': {
      id: '/_app/kontrak'
      path: '/kontrak'
      fullPath: '/kontrak'
      preLoaderRoute: typeof AppKontrakRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financial': {
      id: '/_app/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof AppFinancialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinancialRoute: typeof AppFinancialRoute
  AppKontrakRoute: typeof AppKontrakRoute
  AppProposalRoute: typeof AppProposalRoute
  AppQuizRoute: typeof AppQuizRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSopRoute: typeof AppSopRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinancialRoute: AppFinancialRoute,
  AppKontrakRoute: AppKontrakRoute,
  AppProposalRoute: AppProposalRoute,
  AppQuizRoute: AppQuizRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSopRoute: AppSopRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppWhatsappRoute: AppWhatsappRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
